import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['test/**/*.test.ts'],
    exclude: [
      'test/database.test.ts',
      'test/readiness.test.ts',
      'test/communities-signals.migration.test.ts',
      'test/communities-signals.seed.test.ts',
      'test/communities-signals.constraints.test.ts',
      'test/communities-signals.repository.test.ts',
      'test/communities-signals.api.test.ts',
      'test/signal-confirmation.migration.test.ts',
      'test/signal-confirmation.seed.test.ts',
      'test/signal-confirmation.repository.test.ts',
      'test/signal-confirmation.api.test.ts',
      'test/signal-confirmation.persistence.test.ts',
      'test/signal-confirmation.access.test.ts',
      'test/account-identity.migration.test.ts',
      'test/account-identity.repository.test.ts',
      'test/account-identity.fixtures.test.ts',
      'test/account-password-credentials.repository.test.ts',
      'test/auth-ceremony.migration.test.ts',
      'test/auth-ceremony.repository.test.ts',
      'test/auth-ceremony.fixtures.test.ts',
      'test/email-verification.api.test.ts',
      'test/email-verification.migration.test.ts',
      'test/password-setup.api.test.ts',
      'test/password-authentication.api.test.ts',
      'test/password-authentication.migration.test.ts',
      'test/password-change.api.test.ts',
      'test/password-change.migration.test.ts',
      'test/passkey-registration.api.test.ts',
      'test/passkey-registration.migration.test.ts',
      'test/passkey-authentication.api.test.ts',
      'test/passkey-authentication.migration.test.ts',
      'test/account-recovery.api.test.ts',
      'test/account-recovery.migration.test.ts',
      'test/passkey-management.api.test.ts',
      'test/passkey-management.migration.test.ts',
      'test/membership.migration.test.ts',
      'test/membership.google-play.migration.test.ts',
      'test/membership.google-play-provision.integration.test.ts',
      'test/membership.google-play.verify-and-provision.integration.test.ts',
      'test/membership.google-play.purchase.api.test.ts',
      'test/membership.finalize-paid-pending-binding.migration.test.ts',
      'test/membership.finalize-paid-pending-binding.integration.test.ts',
      'test/membership.finalize-after-eligibility.api.test.ts',
      'test/membership.transitions.integration.test.ts',
      'test/membership.idempotency.integration.test.ts',
      'test/membership.stale.integration.test.ts',
      'test/membership.concurrency.integration.test.ts',
      'test/membership.reconcile.integration.test.ts',
      'test/membership.api.test.ts',
      'test/membership.confirmation.api.test.ts',
      'test/discussion-session.api.test.ts',
      'test/discussion-session.media.api.test.ts',
      'test/discussion-session.migration.test.ts',
      'test/membership.audit.integration.test.ts',
      'test/account-moderation.api.test.ts',
      'test/local-eligibility.api.test.ts',
      'test/community-commitment.api.test.ts',
      'test/signal-submission.api.test.ts',
      'test/signal-moderation.api.test.ts',
      'test/billing.migration.test.ts',
      'test/billing.checkout.api.test.ts',
      'test/billing.portal.api.test.ts',
      'test/billing.customer.integration.test.ts',
      'test/billing.webhook.events.integration.test.ts',
      'test/billing.webhook.signature.test.ts',
      'test/ops.migration-ledger.integration.test.ts',
      'test/ops.staging-seed.integration.test.ts',
      'test/ops.mark-account-owner.integration.test.ts',
      'test/staging-inspection.integration.test.ts',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
    },
  },
});
