import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'test/database.test.ts',
      'test/readiness.test.ts',
      'test/communities-signals.migration.test.ts',
      'test/communities-signals.seed.test.ts',
      'test/communities-signals.constraints.test.ts',
      'test/communities-signals.repository.test.ts',
      'test/communities-signals.api.test.ts',
      'test/signal-confirmation.migration.test.ts',
      'test/signal-confirmation.seed.test.ts',
      'test/signal-confirmation.repository.test.ts',
      'test/signal-confirmation.api.test.ts',
      'test/signal-confirmation.persistence.test.ts',
      'test/signal-confirmation.access.test.ts',
      'test/account-identity.migration.test.ts',
      'test/account-identity.repository.test.ts',
      'test/account-identity.fixtures.test.ts',
      'test/auth-ceremony.migration.test.ts',
      'test/auth-ceremony.repository.test.ts',
      'test/auth-ceremony.fixtures.test.ts',
      'test/email-verification.api.test.ts',
      'test/email-verification.migration.test.ts',
      'test/passkey-registration.api.test.ts',
      'test/passkey-registration.migration.test.ts',
      'test/passkey-authentication.api.test.ts',
      'test/passkey-authentication.migration.test.ts',
      'test/account-recovery.api.test.ts',
      'test/account-recovery.migration.test.ts',
      'test/passkey-management.api.test.ts',
      'test/passkey-management.migration.test.ts',
      'test/membership.migration.test.ts',
      'test/membership.transitions.integration.test.ts',
      'test/membership.idempotency.integration.test.ts',
      'test/membership.stale.integration.test.ts',
      'test/membership.concurrency.integration.test.ts',
      'test/membership.reconcile.integration.test.ts',
      'test/membership.api.test.ts',
      'test/membership.confirmation.api.test.ts',
      'test/membership.audit.integration.test.ts',
    ],
    fileParallelism: false,
    poolOptions: {
      threads: {
        singleThread: true,
      },
    },
    testTimeout: 60_000,
    hookTimeout: 60_000,
  },
});
