/** Passkey authentication and session runtime policy (Slice 4). */

export const PASSKEY_AUTHENTICATION_CHALLENGE_TTL_MINUTES = 5;
export const PASSKEY_AUTHENTICATION_TIMEOUT_MS =
  PASSKEY_AUTHENTICATION_CHALLENGE_TTL_MINUTES * 60_000;

export const PASSKEY_AUTHENTICATION_CHALLENGE_HASH_KEY_MIN_LENGTH = 32;
export const SESSION_TOKEN_HASH_KEY_MIN_LENGTH = 32;

export const DEFAULT_WEB_SESSION_COOKIE_NAME = '__Host-Http-town_session';

export const SESSION_TOUCH_MIN_INTERVAL_MS = 5 * 60_000;

export const ANONYMOUS_CLIENT_KEY_MIN_LENGTH = 16;
export const ANONYMOUS_CLIENT_KEY_MAX_LENGTH = 128;

export const OPTIONS_IP_LIMIT_15M = 20;
export const OPTIONS_IP_LIMIT_24H = 100;
export const OPTIONS_CLIENT_LIMIT_15M = 10;
export const ASSERTION_CREDENTIAL_LIMIT_30M = 10;
export const ASSERTION_IP_LIMIT_30M = 30;
