import {
  SETUP_GRANT_TTL_MINUTES,
  SESSION_ABSOLUTE_TIMEOUT_HOURS,
  SESSION_IDLE_TIMEOUT_MINUTES,
  SENSITIVE_REAUTH_FRESHNESS_MINUTES,
} from '../policy.js';

function sortValue(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortValue);
  }
  if (value !== null && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    const sorted: Record<string, unknown> = {};
    for (const key of Object.keys(record).sort((a, b) => a.localeCompare(b))) {
      sorted[key] = sortValue(record[key]);
    }
    return sorted;
  }
  return value;
}

export function serializeAuthenticationCeremonyContract(document: unknown): string {
  return `${JSON.stringify(sortValue(document), null, 2)}\n`;
}

export function generateAuthenticationCeremonyContractDocument(): unknown {
  return {
    contractVersion: '1.0.0',
    title: 'TOWN Authentication Ceremony Foundation V1',
    description:
      'Architecture contract for ceremony data/session foundation, email verification runtime (including Resend delivery), initial password setup runtime (Model B), first-passkey WebAuthn registration runtime, passkey authentication session runtime, flag-gated public password sign-in runtime, bounded account recovery runtime, and session-authenticated passkey management / security reauthentication runtime. Recovery login sessions, membership, and JWTs remain out of scope.',
    status: 'partially_implemented',
    implementedLiveRoutes: true,
    implementedRoutes: [
      'POST /v1/account/email-verifications',
      'POST /v1/account/email-verifications/complete',
      'POST /v1/account/password',
      'POST /v1/account/passkeys/registration/options',
      'POST /v1/account/passkeys/registration/verify',
      'POST /v1/authentication/passkeys/options',
      'POST /v1/authentication/passkeys/verify',
      'POST /v1/authentication/password',
      'GET /v1/authentication/session',
      'POST /v1/authentication/session/rotate',
      'POST /v1/authentication/logout',
      'POST /v1/authentication/logout-all',
      'POST /v1/account/recovery',
      'POST /v1/account/recovery/verify-email',
      'POST /v1/account/recovery/passkeys/registration/options',
      'POST /v1/account/recovery/passkeys/registration/verify',
      'GET /v1/account/passkeys',
      'POST /v1/account/security/reauthentication/passkeys/options',
      'POST /v1/account/security/reauthentication/passkeys/verify',
      'POST /v1/account/passkeys/add/options',
      'POST /v1/account/passkeys/add/verify',
      'PATCH /v1/account/passkeys/:passkeyId',
      'DELETE /v1/account/passkeys/:passkeyId',
    ],
    slice:
      'ceremony_data_and_session_foundation_plus_email_verification_initial_password_setup_webauthn_registration_passkey_authentication_password_sign_in_account_recovery_and_passkey_management_runtime',
    accountLifecycle: {
      statuses: [
        'pending_email',
        'pending_password',
        'pending_passkey',
        'active',
        'suspended',
        'closed',
      ],
      setupTransitions: [
        'pending_email -> pending_passkey',
        'pending_email -> pending_password',
        'pending_password -> pending_passkey',
        'pending_passkey -> active',
      ],
      activationRequires: [
        'verified primary email',
        'at least one active passkey',
        'linked civic actor',
        'webauthn user handle',
      ],
    },
    domainSeparation: {
      accountIdentity:
        'Account shell, verified email, optional password credential, passkeys, challenges, recovery grants',
      civicActor: 'Local civic participation identity; optionally linked 1:1 to an account',
      authenticationCeremony:
        'Challenges, purpose-bound setup grants, WebAuthn challenge records, rate limits',
      authenticatedSession:
        'Opaque server-side account_sessions; not membership or civic entitlement',
      localVerification: 'Out of scope',
      membershipEntitlement: 'Out of scope',
    },
    setupGrants: {
      table: 'town.setup_grants',
      purpose: ['initial_password_setup', 'initial_passkey_registration'],
      ttlMinutes: SETUP_GRANT_TTL_MINUTES,
      storage: 'token_hash only; raw tokens never stored',
      semantics: [
        'Restricted pre-authentication authority; purpose-bound and never authorizes both password setup and passkey registration',
        'initial_password_setup requires account status pending_password',
        'initial_passkey_registration requires account status pending_passkey',
        'Not a session',
        'Cannot access normal account APIs',
        'Cannot perform civic actions',
        'Cannot authorize membership operations',
        'Cannot create a session',
        'Active only when unconsumed, unrevoked, unexpired, and account status matches the grant purpose',
        'Single-use consumption is concurrency-safe',
      ],
    },
    accountSessions: {
      table: 'town.account_sessions',
      clientTypes: ['web', 'mobile'],
      storage: 'token_hash only; raw session tokens never stored',
      idleTimeoutMinutes: SESSION_IDLE_TIMEOUT_MINUTES,
      absoluteTimeoutHours: SESSION_ABSOLUTE_TIMEOUT_HOURS,
      sensitiveReauthFreshnessMinutes: SENSITIVE_REAUTH_FRESHNESS_MINUTES,
      semantics: [
        'Opaque server-side sessions for authenticated web and mobile clients',
        'Do not imply membership, payment, local verification, civic entitlement, or Stripe state',
        'Creation requires active account, verified primary email, at least one active passkey, and linked civic actor',
        'Setup grants and recovery grants cannot create sessions',
        'Ordinary activity may extend idle_expires_at but never absolute_expires_at or authenticated_at',
        'idle_expires_at must never exceed absolute_expires_at',
      ],
      rotation: [
        'Replacement session and old-session revocation occur atomically',
        'Old revocation reason is rotated',
        'Old token becomes unusable immediately',
        'Replacement receives a new unique token hash',
        'Exactly one concurrent rotation may succeed',
        'Rotation without reauthentication preserves created_at and authenticated_at',
        'Ordinary rotation may extend idle expiry from the rotation time without extending absolute expiry',
      ],
      revocation: {
        reasons: [
          'logout',
          'logout_all',
          'rotated',
          'account_suspended',
          'account_closed',
          'recovery_completed',
          'credential_compromised',
          'security_version_changed',
          'passkey_added',
          'passkey_revoked',
        ],
        operations: [
          'revoke one session',
          'revoke all sessions for account',
          'revoke all other sessions for account',
        ],
        notes: [
          'Repeated revocation is deterministic and safe',
          'Logout routes revoke one current session or all active sessions for the authenticated account',
          'Repository support exists for suspending/closing accounts by revoking all sessions; account administration routes are out of scope',
        ],
      },
    },
    sessionRuntimePolicy: {
      status: 'implemented',
      featureFlag: 'PASSKEY_AUTHENTICATION_ENABLED or PASSWORD_SIGN_IN_ENABLED',
      webCookie: {
        name: '__Host-Http-town_session',
        source: 'WEB_SESSION_COOKIE_NAME',
        attributes: {
          Secure: true,
          HttpOnly: true,
          SameSite: 'Lax',
          Path: '/',
          Domain: null,
          MaxAge: 'derived from account_sessions.absolute_expires_at',
        },
        responseBody: 'web verify and web rotate return only {status:AUTHENTICATED}',
        csrf: 'Mutative web-cookie routes require Origin in WEBAUTHN_ALLOWED_ORIGINS or Sec-Fetch-Site same-origin/same-site',
      },
      mobileTransport: {
        authorization: 'Authorization: Session <opaque-token>',
        tokenResponse:
          'mobile verify and mobile rotate return sessionToken plus sessionExpiresAt in JSON and never Set-Cookie',
      },
      transportSeparation: [
        'Web sessions are extracted only from the configured cookie name',
        'Mobile sessions are extracted only from Authorization: Session',
        'Raw tokens, cookies, and Authorization headers are never logged intentionally',
      ],
      signInIndependence: [
        'Passkey options and verify are gated only by PASSKEY_AUTHENTICATION_ENABLED',
        'Password sign-in is gated only by PASSWORD_SIGN_IN_ENABLED',
        'Shared session introspection, rotation, logout, and logout-all are available when either flag is enabled',
      ],
    },
    ceremonyRateLimits: {
      table: 'town.ceremony_rate_limits',
      storage: 'subject_hash only; raw email, IP, credential id, and tokens never stored',
      uniqueness: ['scope', 'subject_hash', 'window_started_at'],
      scopes: [
        'email_verification_request_email',
        'email_verification_request_ip',
        'email_verification_attempt_challenge',
        'email_verification_attempt_email_ip',
        'password_setup_grant',
        'password_sign_in_ip',
        'password_sign_in_email',
        'password_change_account',
        'passkey_options_ip',
        'passkey_options_client',
        'passkey_assertion_credential',
        'passkey_assertion_ip',
        'recovery_request_email',
        'recovery_request_ip',
        'setup_options_grant',
        'setup_verification_grant',
        'recovery_options_grant',
        'recovery_verification_grant',
        'recovery_email_attempt_challenge',
        'recovery_email_attempt_email_ip',
        'passkey_inventory_account',
        'passkey_reauthentication_options_session',
        'passkey_reauthentication_verify_session',
        'passkey_registration_options_session',
        'passkey_registration_verify_session',
        'passkey_rename_account',
        'passkey_revoke_account',
      ],
      semantics: [
        'Persistent atomic counters for ceremony-specific abuse controls',
        'password_setup_grant is enforced for initial password setup',
        'password_sign_in_ip and password_sign_in_email are enforced for public password sign-in',
        'password_change_account is enforced for session-authenticated password change',
        'setup_options_grant and setup_verification_grant are enforced for WebAuthn registration',
        'recovery_request_*, recovery_email_attempt_*, recovery_options_grant, and recovery_verification_grant are enforced for account recovery',
        'passkey_inventory_account and manage_* / passkey_rename_account / passkey_revoke_account are enforced for passkey management',
        'No Redis',
        'Subjects are pre-hashed only',
      ],
    },
    identitySecurityEventTypes: {
      preserved: [
        'email_verification_requested',
        'email_verified',
        'passkey_registered',
        'passkey_used',
        'passkey_revoked',
        'recovery_requested',
        'recovery_completed',
        'account_suspended',
        'account_closed',
        'authentication_failed',
        'session_created',
        'session_rotated',
        'session_revoked',
        'counter_anomaly_detected',
        'rate_limit_triggered',
      ],
      added: ['passkey_registration_failed', 'account_activated'],
      slice4Added: ['authentication_succeeded'],
      slice5Added: ['recovery_email_verified', 'recovery_registration_failed'],
      slice6Added: [
        'passkey_inventory_viewed',
        'passkey_management_changed',
        'passkey_reauthentication_started',
        'passkey_reauthentication_succeeded',
        'passkey_reauthentication_failed',
        'passkey_renamed',
      ],
      passwordSetupAdded: ['password_credential_created'],
      passwordChangeAdded: ['password_credential_changed', 'password_change_failed'],
    },
    grantVersusSessionDistinction: {
      setupGrant:
        'Purpose-bound restricted setup authority for initial_password_setup or initial_passkey_registration; never both; not authenticated access',
      recoveryGrant:
        'Restricted recovery authority; revokes sessions; does not create a normal session',
      accountSession: 'Opaque authenticated session after eligible active account authentication',
    },
    cookiePolicy: {
      status: 'implemented',
      notes: [
        'Web clients use HttpOnly Secure SameSite cookies binding an opaque session token',
        'Cookie route responses never expose raw web session tokens in JSON',
        'CSRF protections are enforced for mutative cookie-authenticated session routes',
      ],
    },
    rpIdAndOriginPolicy: {
      status: 'implemented',
      featureFlag: 'WEBAUTHN_REGISTRATION_ENABLED',
      productionRpId: 'towncivic.org',
      initialProductionWebOrigin: 'https://towncivic.org',
      stagingRpId: 'staging.towncivic.org',
      stagingOrigin: 'https://staging.towncivic.org',
      developmentRpId: 'localhost',
      notes: [
        'RP ID and allowed origins are server-owned configuration',
        'Never derived from Host, Origin, Forwarded, or X-Forwarded-* headers',
        'Wildcard origins are prohibited',
        'Staging, development, and production credentials remain isolated',
        'Temporary Railway, preview, GitHub Pages, www, and API origins are rejected for production',
      ],
    },
    emailVerificationRuntime: {
      status: 'implemented',
      featureFlag: 'EMAIL_VERIFICATION_ENABLED',
      routes: [
        'POST /v1/account/email-verifications',
        'POST /v1/account/email-verifications/complete',
      ],
      codePolicy: {
        length: 6,
        ttlMinutes: 10,
        maxAttempts: 5,
        storage: 'HMAC-SHA-256 secret_hash only',
      },
      antiEnumeration: true,
      createsSession: false,
      activatesAccount: false,
      transitions: ['pending_email -> pending_passkey'],
      issues: {
        pending_email: 'restricted setup grant initial_passkey_registration',
        pending_password_reentry: 'restricted setup grant initial_password_setup',
        pending_passkey_reentry: 'restricted setup grant initial_passkey_registration',
      },
      deliveryModes: ['test', 'development', 'resend'],
    },
    passwordSetupRuntime: {
      status: 'implemented',
      featureFlag: 'PASSWORD_AUTH_ENABLED',
      routes: ['POST /v1/account/password'],
      authorization: 'Authorization: SetupGrant <opaque-token> with purpose initial_password_setup',
      requiredAccountStatus: 'pending_password',
      createsSession: false,
      activatesAccount: false,
      success: {
        status: 'PASSWORD_SET',
        transition: 'pending_password -> pending_passkey',
        handoff: 'fresh restricted setup grant initial_passkey_registration',
      },
      publicErrorCode: 'PASSWORD_SETUP_FAILED',
      rateLimits: {
        password_setup_grant: 5,
      },
      securityEvent: 'password_credential_created',
    },
    passwordSignInRuntime: {
      status: 'implemented',
      featureFlag: 'PASSWORD_SIGN_IN_ENABLED',
      routes: ['POST /v1/authentication/password'],
      independentOf: ['PASSWORD_AUTH_ENABLED', 'PASSKEY_AUTHENTICATION_ENABLED'],
      createsAccount: false,
      createsCredential: false,
      createsSession: true,
      sharedSessionLifecycle:
        'GET/POST session introspection, rotation, logout, and logout-all are available when PASSWORD_SIGN_IN_ENABLED or PASSKEY_AUTHENTICATION_ENABLED is true',
      requiredAccountStatus: 'active',
      requires: [
        'unrevoked canonical email',
        'verified primary email',
        'active password credential',
        'session eligibility (active passkey + linked civic actor)',
      ],
      antiEnumeration: true,
      publicErrorCode: 'AUTHENTICATION_FAILED',
      dummyVerification: 'in-memory Argon2id hash with production parameters; never stored',
      sessionIssuance: {
        web: 'Secure HttpOnly SameSite=Lax cookie only; no token in JSON',
        mobile: 'sessionToken plus sessionExpiresAt JSON only; no Set-Cookie',
      },
      rateLimits: {
        password_sign_in_ip_30m: 30,
        password_sign_in_email_30m: 10,
      },
      neverReturns: ['accountId', 'email', 'credentialId', 'password', 'passwordHash'],
    },
    passwordChangeRuntime: {
      status: 'implemented',
      featureFlag: 'PASSWORD_CHANGE_ENABLED',
      routes: ['POST /v1/account/password/change'],
      independentOf: [
        'PASSWORD_AUTH_ENABLED',
        'PASSWORD_SIGN_IN_ENABLED',
        'PASSKEY_AUTHENTICATION_ENABLED',
      ],
      authorization: 'active Session (cookie or Authorization: Session)',
      requiresCurrentPassword: true,
      freshAuthenticationAgeCheck: false,
      createsAccount: false,
      createsSession: false,
      rotatesSession: true,
      revokesOtherSessionsReason: 'password_changed',
      requiredAccountStatus: 'active',
      publicErrorCode: 'PASSWORD_CHANGE_FAILED',
      successStatus: 'PASSWORD_CHANGED',
      sessionIssuance: {
        web: 'replacement Secure HttpOnly SameSite=Lax cookie only; no token in JSON',
        mobile: 'sessionToken plus sessionExpiresAt JSON only; no Set-Cookie',
      },
      rateLimits: {
        password_change_account_30m: 10,
      },
      securityEvents: ['password_credential_changed', 'password_change_failed'],
      neverReturns: ['accountId', 'email', 'credentialId', 'password', 'passwordHash'],
    },
    webauthnRegistrationRuntime: {
      status: 'implemented',
      featureFlag: 'WEBAUTHN_REGISTRATION_ENABLED',
      dependency: '@simplewebauthn/server@13.3.2',
      routes: [
        'POST /v1/account/passkeys/registration/options',
        'POST /v1/account/passkeys/registration/verify',
      ],
      authorization: 'Authorization: SetupGrant <opaque-token>',
      ceremonyReference: 'registrationCeremonyId (non-secret challenge row id)',
      optionsPolicy: {
        attestationType: 'none',
        residentKey: 'required',
        requireResidentKey: true,
        userVerification: 'required',
        supportedAlgorithmIDs: [-7, -257],
        challengeTtlMinutes: 5,
      },
      userHandle: {
        bytes: 32,
        storage: 'town.accounts.webauthn_user_handle',
        opaque: true,
        immutable: true,
      },
      challengeStorage: 'HMAC-SHA-256 challenge_hash only; raw challenge never stored',
      activation: {
        atomic: true,
        createsSession: false,
        createsCivicActor: true,
        actorCommunityId: null,
        transition: 'pending_passkey -> active',
        requiresActivePasswordCredential: true,
      },
      publicErrorCode: 'PASSKEY_REGISTRATION_FAILED',
      rateLimits: {
        setup_options_grant: 5,
        setup_verification_grant: 5,
      },
    },
    passkeyAuthenticationRuntime: {
      status: 'implemented',
      featureFlag: 'PASSKEY_AUTHENTICATION_ENABLED',
      dependency: '@simplewebauthn/server@13.3.2',
      routes: [
        'POST /v1/authentication/passkeys/options',
        'POST /v1/authentication/passkeys/verify',
        'GET /v1/authentication/session',
        'POST /v1/authentication/session/rotate',
        'POST /v1/authentication/logout',
        'POST /v1/authentication/logout-all',
      ],
      ceremonyReference: 'authenticationCeremonyId (non-secret challenge row id)',
      optionsPolicy: {
        allowCredentials: 'omitted to avoid account enumeration',
        userVerification: 'required',
        challengeTtlMinutes: 5,
      },
      challengeStorage: 'HMAC-SHA-256 challenge_hash only; raw challenge never stored',
      assertionPolicy: {
        expectedOrigins: 'WEBAUTHN_ALLOWED_ORIGINS',
        expectedRpId: 'WEBAUTHN_RP_ID',
        userVerification: 'required',
        signCounter:
          'counter 0->0 and increasing counters accepted; repeated or decreasing positive counters are rejected and emit counter_anomaly_detected',
        backupState:
          'backup_eligible is retained; backed_up is monotonic and synced/backed-up passkeys are never downgraded',
      },
      sessionIssuance: {
        web: 'Secure HttpOnly SameSite=Lax cookie only; no token in JSON',
        mobile: 'sessionToken plus sessionExpiresAt JSON only; no Set-Cookie',
      },
      publicErrorCode: 'AUTHENTICATION_FAILED',
      freshnessErrorCode: 'RECENT_AUTHENTICATION_REQUIRED',
      rateLimits: {
        optionsIp15m: 20,
        optionsIp24h: 100,
        optionsAnonymousClient15m: 10,
        assertionCredential30m: 10,
        assertionIp30m: 30,
      },
    },
    accountRecoveryRuntime: {
      status: 'implemented',
      featureFlag: 'ACCOUNT_RECOVERY_ENABLED',
      routes: [
        'POST /v1/account/recovery',
        'POST /v1/account/recovery/verify-email',
        'POST /v1/account/recovery/passkeys/registration/options',
        'POST /v1/account/recovery/passkeys/registration/verify',
      ],
      eligibility: 'active account with verified primary email matching the request',
      codePolicy: {
        length: 6,
        ttlMinutes: 10,
        maxAttempts: 5,
        storage: 'HMAC-SHA-256 secret_hash only; binds challengeId+purpose+accountId+code',
      },
      grantPolicy: {
        ttlMinutes: 15,
        authorization: 'Authorization: RecoveryGrant <opaque-token>',
        storage: 'token_hash only; raw tokens never stored',
        createsSession: false,
      },
      passkeyRegistration: {
        purpose: 'recover_register',
        ceremonyReference: 'recoveryCeremonyId (non-secret challenge row id)',
        reuseExistingUserHandle: true,
        excludeCredentials: 'all active passkeys',
        attestationType: 'none',
        residentKey: 'required',
        userVerification: 'required',
        existingPasskeysRemainActive: true,
      },
      completion: {
        atomic: true,
        createsSession: false,
        revokesAllSessionsReason: 'recovery_completed',
        setsRecoveryCompletedAt: true,
        accountRemainsActive: true,
      },
      antiEnumeration: true,
      publicErrorCodes: ['INVALID_OR_EXPIRED_CHALLENGE', 'RECOVERY_NOT_AUTHORIZED'],
      deliveryModes: ['test', 'development'],
      rateLimits: {
        requestEmail24h: 3,
        requestIp24h: 10,
        attemptChallenge: 5,
        attemptEmailIp30m: 10,
        recovery_options_grant: 5,
        recovery_verification_grant: 5,
      },
    },
    passkeyManagementRuntime: {
      status: 'implemented',
      featureFlag: 'PASSKEY_AUTHENTICATION_ENABLED',
      authorization: [
        'active Session (cookie or Authorization: Session) required for all management routes',
        'SetupGrant cannot authorize any passkey management route',
        'RecoveryGrant cannot authorize any passkey management route',
        'Bearer rejected',
      ],
      routes: [
        'GET /v1/account/passkeys',
        'POST /v1/account/security/reauthentication/passkeys/options',
        'POST /v1/account/security/reauthentication/passkeys/verify',
        'POST /v1/account/passkeys/add/options',
        'POST /v1/account/passkeys/add/verify',
        'PATCH /v1/account/passkeys/:passkeyId',
        'DELETE /v1/account/passkeys/:passkeyId',
      ],
      distinctFromInitialRegistration: {
        initialSetupRoutes: [
          'POST /v1/account/passkeys/registration/options',
          'POST /v1/account/passkeys/registration/verify',
        ],
        initialSetupAuthorization: 'SetupGrant only',
        addPasskeyRoutes: [
          'POST /v1/account/passkeys/add/options',
          'POST /v1/account/passkeys/add/verify',
        ],
        addPasskeyAuthorization: 'active Session plus fresh authentication only',
      },
      freshness: {
        field: 'account_sessions.fresh_authenticated_at',
        windowMinutes: 10,
        requiredFor: ['add passkey', 'revoke passkey'],
        notRequiredFor: ['inventory', 'rename'],
      },
      reauthentication: {
        purpose: 'manage_passkeys_authenticate',
        allowCredentials: 'all active passkeys',
        userVerification: 'required',
        challengeTtlMinutes: 5,
        sessionBound: true,
        successStatus: 'FRESH_AUTHENTICATION_CONFIRMED',
      },
      addPasskey: {
        purpose: 'manage_passkeys_register',
        reuseExistingUserHandle: true,
        excludeCredentials: 'all active passkeys',
        revokeOtherSessionsReason: 'passkey_added',
        preserveFreshnessOnRotation: true,
      },
      inventory: {
        opaquePublicId: true,
        neverExposes: [
          'credentialId',
          'publicKey',
          'aaguid',
          'signCount',
          'userHandle',
          'internal id',
        ],
      },
      revoke: {
        lastActiveProtection: true,
        cannotRevokeCurrentAuthenticatedCredential: true,
        revokeOtherSessionsReason: 'passkey_revoked',
      },
      publicErrorCodes: [
        'SESSION_NOT_AUTHORIZED',
        'FRESH_AUTHENTICATION_REQUIRED',
        'PASSKEY_NOT_FOUND',
        'PASSKEY_REGISTRATION_FAILED',
        'PASSKEY_REAUTHENTICATION_FAILED',
        'LAST_ACTIVE_PASSKEY_REQUIRED',
        'RATE_LIMITED',
      ],
      rateLimits: {
        passkey_inventory_account_15m: 60,
        passkey_reauthentication_options_session_15m: 10,
        passkey_reauthentication_verify_session_15m: 5,
        passkey_registration_options_session_15m: 5,
        passkey_registration_verify_session_15m: 5,
        passkey_rename_account_24h: 20,
        passkey_revoke_account_24h: 10,
      },
    },
    explicitExclusions: [
      'recovery login / session issuance from recovery',
      'production recovery email delivery',
      'password recovery / reset / change',
      'phone sign-in',
      'JWTs',
      'membership',
      'Stripe',
      'local verification',
      'Railway',
      'web integration',
      'mobile integration',
      'deployment',
      'Redis',
    ],
  };
}
