/** Passkey management / security reauthentication policy (Slice 6). */

export const MANAGE_PASSKEYS_CHALLENGE_TTL_MINUTES = 5;
export const MANAGE_PASSKEYS_TIMEOUT_MS = MANAGE_PASSKEYS_CHALLENGE_TTL_MINUTES * 60_000;

export const PASSKEY_FRESHNESS_MINUTES = 10;

export const PASSKEY_LABEL_MAX_CODE_POINTS = 64;

export const PASSKEY_INVENTORY_ACCOUNT_LIMIT_15M = 60;
export const PASSKEY_REAUTHENTICATION_OPTIONS_SESSION_LIMIT_15M = 10;
export const PASSKEY_REAUTHENTICATION_VERIFY_SESSION_LIMIT_15M = 5;
export const PASSKEY_REGISTRATION_OPTIONS_SESSION_LIMIT_15M = 5;
export const PASSKEY_REGISTRATION_VERIFY_SESSION_LIMIT_15M = 5;
export const PASSKEY_RENAME_ACCOUNT_LIMIT_24H = 20;
export const PASSKEY_REVOKE_ACCOUNT_LIMIT_24H = 10;

export const WEBAUTHN_SUPPORTED_ALGORITHM_IDS = [-7, -257] as const;

export const CIVIC_ACTOR_DISPLAY_LABEL = 'TOWN member';
